# Site settings
title: Corporate Chaplaincy Consulting
description:
baseurl: "/corpchaps.com" 
permalink: /:categories/:title/
url: "http://capital-chaplains.github.io/corpchaps.com/"
include: ['_css','_js','_img']
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
gems:
  - jekyll-redirect-from

# Build settings
markdown: kramdown
