# Site settings
title: Corporate Chaplaincy Consulting
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.corpchaps.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
